name: Publish Package
on:
  workflow_dispatch:
    branches: [main]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: pnpm install
      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
